import hashlib
import secrets

# secp256k1 parameters
P = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F
N = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
A = 0
B = 7

Gx = 55066263022277343669578718895168534326250603453777594175500187360389116729240
Gy = 32670510020758816978083085130507043184471273380659243275938904335757337482424
G = (Gx, Gy)
# you can change these, but it would not be secp256k1 anymore, and ideally you would need to verify the resulting curve has good cryptographic properties. There are many bad curves with exploitable weaknesses
# note that the parameters above P,A,B,G,N for secp256k1 satisfy that
#   arithmetic is efficient
#   the curve has no known weaknesses
#   the subgroup generated by G is prime
#   the subgroup is extremely large (~2**256 elements)
#   the cofactor is 1 (which simplifies many protocols)
#-----------------------------------

def modinv(x, m):
    return pow(x, -1, m)

def point_add(P1, P2):
    if P1 is None:
        return P2
    if P2 is None:
        return P1

    x1, y1 = P1
    x2, y2 = P2

    if x1 == x2 and (y1 + y2) % P == 0:
        return None

    if P1 == P2:
        lam = (3 * x1 * x1) * modinv(2 * y1 % P, P)
    else:
        lam = (y2 - y1) * modinv((x2 - x1) % P, P)

    lam %= P
    x3 = (lam * lam - x1 - x2) % P
    y3 = (lam * (x1 - x3) - y1) % P
    return (x3, y3)

def scalar_mult(k, point):
    result = None
    addend = point

    while k:
        if k & 1:
            result = point_add(result, addend)
        addend = point_add(addend, addend)
        k >>= 1

    return result

def tagged_hash(tag, *msgs):
    taghash = hashlib.sha256(tag.encode()).digest()
    h = hashlib.sha256()
    h.update(taghash)
    h.update(taghash)
    for m in msgs:
        h.update(m)
    return h.digest()

def int_to_bytes(x):
    return x.to_bytes(32, "big")

def point_to_bytes(P):
    return int_to_bytes(P[0])

def challenge(R, Ppub, msg):
    return int.from_bytes(
        tagged_hash(
            "BIP0340/challenge",
            point_to_bytes(R),
            point_to_bytes(Ppub),
            msg,
        ),
        "big",
    ) % N

def keygen():
    sk = secrets.randbelow(N - 1) + 1
    pk = scalar_mult(sk, G)
    return sk, pk

def sign(sk, msg):
    Ppub = scalar_mult(sk, G)

    k = int.from_bytes(
        tagged_hash(
            "BIP0340/nonce",
            int_to_bytes(sk),
            msg,
        ),
        "big",
    ) % N

    if k == 0:
        raise ValueError("bad nonce")

    R = scalar_mult(k, G)

    # Force even Y (BIP340 convention)
    if R[1] & 1:
        k = N - k
        R = scalar_mult(k, G)

    e = challenge(R, Ppub, msg)
    s = (k + e * sk) % N

    return (R[0], s)

def verify(pk, msg, sig):
    rx, s = sig

    if not (0 <= rx < P and 0 <= s < N):
        return False

    y_sq = (pow(rx, 3, P) + 7) % P
    y = pow(y_sq, (P + 1) // 4, P)

    if (y * y) % P != y_sq:
        return False

    if y & 1:
        y = P - y

    R = (rx, y)

    e = challenge(R, pk, msg)

    left = scalar_mult(s, G)
    right = point_add(R, scalar_mult(e, pk))

    return left == right

# --- point encoding (compressed public key style) ---

def bytes_to_int(b):
    return int.from_bytes(b, "big")

def encode_pubkey(P):
    """(x, y) -> 33-byte compressed pubkey"""
    x, y = P
    prefix = b"\x02" if y % 2 == 0 else b"\x03"
    return prefix + int_to_bytes(x)

def decode_pubkey(b):
    """33-byte compressed pubkey -> (x, y)"""
    prefix = b[0]
    x = bytes_to_int(b[1:33])

    y_sq = (pow(x, 3, P) + 7) % P
    y = pow(y_sq, (P + 1) // 4, P)

    # choose correct parity
    if (y % 2 == 0) != (prefix == 2):
        y = P - y

    return (x, y)

def encode_sig(sig):
    """(rx, s) -> 64-byte signature"""
    rx, s = sig
    return int_to_bytes(rx) + int_to_bytes(s)

def decode_sig(b):
    """64-byte signature -> (rx, s)"""
    rx = bytes_to_int(b[:32])
    s = bytes_to_int(b[32:])
    return (rx, s)

def gen_nonce(nbytes=16):
    # Generate a 16-byte (128-bit) random nonce as a hex string
    return secrets.token_hex(nbytes)
